name: jsz
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0-12/1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest 
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        User: ${{ github.event.repository.owner.id }}
    steps:

      - name: Checkout
        run: |
          git clone https://github.com/q609262096/cxk.git ~/cxk
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/cxk
          npm install
          npm install cron
          npm install request
          npm install md5-node
      - name: '运行 【jsz】'
        run: |
          cd ~/cxk   
          node Task/jsz1.js
