name: 中青阅读5

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '20 3-23/2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/q609262096/js.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青阅读5】'
        run: |
          cd ~/js   
          node Task/Youth_AutoRead5.js
